services:
  # PHP-Apache
  kamakura-shokusu_web:
    container_name: kamakura-shokusu_web
    build:
      context: ./kamakura-shokusu_web
      dockerfile: Dockerfile
    ports:
      - "8091:80"
    volumes:
      - "../src_web:/var/www/html"
      - "../datasource/phpini/php.ini:/usr/local/etc/php/php.ini:cached"
    env_file:
      - ../src_web/kamaho-shokusu/.env
    environment:
      TZ: Asia/Tokyo
    networks:
      - network-inner
      - network-db

  # MySQL
  kamakura-shokusu_db:
    container_name: kamakura-shokusu_web_db
    image: mysql:lts
    ports:
      - "3306:3306"
    volumes:
      - "../datasource/database:/var/lib/mysql"
      - "../datasource/dump:/usr/local/dump"
    environment:
      MYSQL_DATABASE: shokusu
      MYSQL_USER: kamakuraadm1n
      MYSQL_PASSWORD: hata220424
      MYSQL_ROOT_PASSWORD: KamakurA
      TZ: Asia/Tokyo
    networks:
      - network-db

networks:
  network-inner:
    name: network-inner
    internal: false
  network-db:
    name: network-db
    internal: false
